spring.application.name=transaction-service

# Server Configuration
server.port=8082

# Spring Application Name (Used as Eureka ID)

# MongoDB Configuration
spring.data.mongodb.database=transactions_db
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Resilience4j Circuit Breaker Configuration
resilience4j.circuitbreaker.instances.accountServiceBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.accountServiceBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.accountServiceBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.accountServiceBreaker.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.accountServiceBreaker.slidingWindowSize=10