spring.application.name=notification-service

# Server Configuration
server.port=8083

# Spring Application Name (Used as Eureka ID)

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true